on:
  workflow_call:
    inputs:
      testing:
        description: "Run unit tests"
        required: true
        type: boolean

jobs:
  build:
    name: Build Project (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add apt.llvm.org repository
      run: |
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc &&
        source /etc/os-release &&
        sudo add-apt-repository -y "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-16 main" &&
        sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install clang llvm clang-tidy  git linux-libc-dev libclang-18-dev libclang-cpp-dev cmake build-essential
    - name: Configure project
      run: mkdir build && cd build && cmake .. -DBUILD_TESTING=1
    - name: Build project
      run: make -j4 
    - name: Run tests
      if: ${{ inputs.testing == true }}
      run: cd build/unit && ctest -j4 --output-on-failure --progress .
